export enum AuthError {
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  USER_INACTIVE = 'AUTH_USER_INACTIVE',
  USER_BLOCKED = 'AUTH_USER_BLOCKED',
  TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  REFRESH_TOKEN_REVOKED = 'AUTH_REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  DEVICE_MISMATCH = 'AUTH_DEVICE_MISMATCH',
  TWO_FACTOR_REQUIRED = 'AUTH_2FA_REQUIRED',
  TWO_FACTOR_INVALID = 'AUTH_2FA_INVALID',
  PHONE_NUMBER_MISMATCH = 'AUTH_PHONE_MISMATCH',
  VERIFICATION_CODE_EXPIRED = 'AUTH_VERIFICATION_CODE_EXPIRED',
  VERIFICATION_CODE_NOT_FOUND = 'AUTH_VERIFICATION_CODE_NOT_FOUND',
  VERIFICATION_CODE_INVALID = 'AUTH_VERIFICATION_CODE_INVALID'
}
