
export const AUTH_SERVICE_TOKEN = Symbol('AUTH_SERVICE_TOKEN');
export const USERS_SERVICE_TOKEN = Symbol('USERS_SERVICE_TOKEN');
export const ROLES_SERVICE_TOKEN = Symbol('ROLES_SERVICE_TOKEN');
export const TOKEN_SERVICE_TOKEN = Symbol('TOKEN_SERVICE_TOKEN');
export const SESSION_SERVICE_TOKEN = Symbol('SESSION_SERVICE_TOKEN');
export const SECURITY_ANALYSIS_SERVICE_TOKEN = Symbol('SECURITY_ANALYSIS_SERVICE_TOKEN');
export const MFA_ORCHESTRATOR_SERVICE_TOKEN = Symbol('MFA_ORCHESTRATOR_SERVICE_TOKEN');
export const PASSWORD_SERVICE_TOKEN = Symbol('PASSWORD_SERVICE_TOKEN');
export const USER_CACHE_SERVICE_TOKEN = Symbol('USER_CACHE_SERVICE_TOKEN');
export const GEO_SERVICE_TOKEN = Symbol('GEO_SERVICE_TOKEN');
export const CRYPTO_UTIL_TOKEN = Symbol('CRYPTO_UTIL_TOKEN');
export const TWO_FACTOR_AUTH_SERVICE_TOKEN = Symbol('TWO_FACTOR_AUTH_SERVICE_TOKEN');
export const REGISTRATION_SERVICE_TOKEN = Symbol('REGISTRATION_SERVICE_TOKEN');
